In [ ]:
import numpy as np
import random
import torch

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [ ]:
my_first_tensor = torch.rand(3, 4, 5)  # или принудительно torch.FloatTensor()
my_first_tensor

tensor([[[2.5520e-01, 2.0596e-01, 8.1774e-01, 6.0871e-02, 5.7741e-01],
         [6.2457e-01, 8.7041e-01, 1.9583e-01, 4.0723e-01, 2.8176e-01],
         [7.2321e-01, 3.1396e-01, 4.3009e-01, 4.3767e-01, 5.0496e-01],
         [3.9120e-01, 7.5441e-01, 3.5368e-01, 5.6801e-01, 4.5781e-01]],

        [[9.4811e-01, 9.5478e-01, 7.4587e-01, 2.6686e-01, 6.6083e-01],
         [4.6966e-01, 5.8996e-01, 5.4560e-02, 3.5448e-01, 1.6377e-01],
         [4.9065e-01, 1.8273e-01, 2.2838e-01, 1.7614e-01, 2.2173e-03],
         [8.1601e-01, 1.3909e-02, 9.1965e-01, 6.2150e-01, 6.7893e-01]],

        [[8.6124e-01, 3.6650e-01, 4.4423e-01, 6.4784e-02, 9.7211e-01],
         [4.1947e-01, 4.6241e-01, 1.0646e-01, 8.3565e-01, 6.0470e-01],
         [8.6808e-01, 6.1220e-01, 3.3889e-01, 1.2296e-04, 9.7576e-01],
         [3.7902e-01, 4.2646e-02, 6.9354e-01, 2.7102e-01, 2.6166e-01]]])

In [ ]:
# 2. Выведите его форму (shape)

In [ ]:
my_first_tensor.size()

torch.Size([3, 4, 5])

In [ ]:
# 3. Приведите его к форме 6х10

In [ ]:
my_first_tensor = my_first_tensor.reshape([6, 10])
my_first_tensor

tensor([[2.5520e-01, 2.0596e-01, 8.1774e-01, 6.0871e-02, 5.7741e-01, 6.2457e-01,
         8.7041e-01, 1.9583e-01, 4.0723e-01, 2.8176e-01],
        [7.2321e-01, 3.1396e-01, 4.3009e-01, 4.3767e-01, 5.0496e-01, 3.9120e-01,
         7.5441e-01, 3.5368e-01, 5.6801e-01, 4.5781e-01],
        [9.4811e-01, 9.5478e-01, 7.4587e-01, 2.6686e-01, 6.6083e-01, 4.6966e-01,
         5.8996e-01, 5.4560e-02, 3.5448e-01, 1.6377e-01],
        [4.9065e-01, 1.8273e-01, 2.2838e-01, 1.7614e-01, 2.2173e-03, 8.1601e-01,
         1.3909e-02, 9.1965e-01, 6.2150e-01, 6.7893e-01],
        [8.6124e-01, 3.6650e-01, 4.4423e-01, 6.4784e-02, 9.7211e-01, 4.1947e-01,
         4.6241e-01, 1.0646e-01, 8.3565e-01, 6.0470e-01],
        [8.6808e-01, 6.1220e-01, 3.3889e-01, 1.2296e-04, 9.7576e-01, 3.7902e-01,
         4.2646e-02, 6.9354e-01, 2.7102e-01, 2.6166e-01]])

In [ ]:
my_first_tensor.size()

torch.Size([6, 10])

In [ ]:
# 4. Создайте случайный IntTensor размера 10

In [ ]:
my_second_tensor = torch.randint(5, (10,), dtype=torch.int32)
my_second_tensor

tensor([3, 2, 1, 2, 3, 3, 1, 0, 4, 2], dtype=torch.int32)

In [ ]:
print(f'Shape: {my_second_tensor.size()}')
print(f'Type: {my_second_tensor.type()}')

Shape: torch.Size([10])
Type: torch.IntTensor


In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [ ]:
multiply = torch.mul(my_first_tensor, my_second_tensor)  # или my_first_tensor*my_second_tensor // или my_first_tensor.mul(my_second_tensor)
multiply

tensor([[7.6561e-01, 4.1192e-01, 8.1774e-01, 1.2174e-01, 1.7322e+00, 1.8737e+00,
         8.7041e-01, 0.0000e+00, 1.6289e+00, 5.6352e-01],
        [2.1696e+00, 6.2793e-01, 4.3009e-01, 8.7535e-01, 1.5149e+00, 1.1736e+00,
         7.5441e-01, 0.0000e+00, 2.2720e+00, 9.1562e-01],
        [2.8443e+00, 1.9096e+00, 7.4587e-01, 5.3371e-01, 1.9825e+00, 1.4090e+00,
         5.8996e-01, 0.0000e+00, 1.4179e+00, 3.2753e-01],
        [1.4719e+00, 3.6547e-01, 2.2838e-01, 3.5228e-01, 6.6519e-03, 2.4480e+00,
         1.3909e-02, 0.0000e+00, 2.4860e+00, 1.3579e+00],
        [2.5837e+00, 7.3299e-01, 4.4423e-01, 1.2957e-01, 2.9163e+00, 1.2584e+00,
         4.6241e-01, 0.0000e+00, 3.3426e+00, 1.2094e+00],
        [2.6042e+00, 1.2244e+00, 3.3889e-01, 2.4593e-04, 2.9273e+00, 1.1370e+00,
         4.2646e-02, 0.0000e+00, 1.0841e+00, 5.2333e-01]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [ ]:
matmultiply = torch.matmul(multiply, multiply.T)
matmultiply

tensor([[11.6793, 12.0747, 12.7210, 10.9323, 16.5976, 12.0744],
        [12.0747, 16.2946, 16.7815, 13.6148, 21.3159, 15.3083],
        [12.7210, 16.7815, 20.9592, 12.6832, 22.1123, 19.1374],
        [10.9323, 13.6148, 12.6832, 16.4935, 17.2764, 10.5674],
        [16.5976, 21.3159, 22.1123, 17.2764, 30.3651, 22.0207],
        [12.0744, 15.3083, 19.1374, 10.5674, 22.0207, 19.7088]])

In [ ]:
matmultiply.size()

torch.Size([6, 6])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [ ]:
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

y = torch.pow(x, 3) + z - 75*t
y.backward()

print(f'({x.grad}, {z.grad}, {t.grad})')


(3.0, 1.0, -75.0)


In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [ ]:
ones_tensor = torch.ones(5, 6)
ones_tensor

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
ones_tensor.size()

torch.Size([5, 6])

In [ ]:
# 9. Переведите его в формат numpy

In [ ]:
ones_tensor = ones_tensor.numpy()
ones_tensor

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
type(ones_tensor)

numpy.ndarray